services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    volumes:
      - "./dbInit/users.sql:/docker-entrypoint-initdb.d/users.sql"

  backend:
    build: .
    image: framework-eval-template:latest
    depends_on:
      - db
